### PR TITLE
Add logic to detect tag groups

### PR DESCRIPTION
**Pull request by LesykMelnychuk**
Added logic to process grouped tags:
GroupedStyle([b, i], attributes)

`<b><i>text</i></b>`  => would be detected as separate style

### CODE REVIEW

**Comment by psharanda** [comment]
Hi there,
Wow, that looks like really useful. Please, could you update PR description with short explanation of what it is done in it?

**Comment by LesykMelnychuk** [comment]
ok

**Comment by psharanda** [comment]
@LesykMelnychuk Could you base your PR on master, not on the other PR? Also tests are required for new features, and I can't approve PR without them

**Comment by LesykMelnychuk** [comment]
Added test

**Comment by psharanda** [comment]
This was addressed in V5. Take a look at Demo snippets

**Pull request closed without merging**
