### PR TITLE
V5

### PR DESCRIPTION
**Pull request by psharanda**

### CODE REVIEW

**Comment by tobi-mb** [comment]
@psharanda Thank you for actively maintaining your project. Can you also change the macOS deployment target to 10.13 as Apple has dropped support for anything lower than that in Xcode 14.3. Thank you very much!

**Comment by tobi-mb** [comment]
@psharanda Ah, you're referring to developers using older Xcode versions here, right? Hm, theoretically you're right, Xcode still does compile despite the warning but in our case, we used Carthage (latest version 0.39.0) for dependency management and that definitely fails for all projects with an unsupported deployment target. Do you think this is a general issue better to be fixed in the Carthage project?

**Comment by tobi-mb** [comment]
Just did another test and it turns out, this warning turns into an error when building with the Release configuration, therefore making it impossible to use the framework with newer versions of Xcode.

**Comment by psharanda** [comment]
> Just did another test and it turns out, this warning turns into an error when building with the Release configuration, therefore making it impossible to use the framework with newer versions of Xcode.

@tobi-mb I've added Cocoapods/SPM/Carthage integration projects in the last commit. Carthage works fine for me if I run it like this:
`carthage update --platform ios --use-xcframeworks`
Archiving those projects is also being successful for me. I can see that popular OSS projects like RxSwift or SnapKit work fine with pre iOS 11 versions

**Comment by tobi-mb** [comment]
@psharanda Thanks for the updates but I was referring to the macOS platform, not iOS. When running `carthage update --platform macOS --use-xcframeworks` I still get the error which is not surprising considering that building for Release already fails within the project and therefore led me to believe that this is not an issue on Carthage's side.

**Comment by psharanda** [comment]
> @psharanda Thanks for the updates but I was referring to the macOS platform, not iOS. When running `carthage update --platform macOS --use-xcframeworks` I still get the error which is not surprising considering that building for Release already fails within the project and therefore led me to believe that this is not an issue on Carthage's side.

@tobi-mb Can you try `carthage update --platform macOS --use-xcframeworks` for v5 branch inside of 'Integration/CarthageDemo' folder? It works for me as well

**Comment by psharanda** [comment]
Carthage is installed via brew and is v0.39.0 for my setup

**Comment by psharanda** [comment]
@tobi-mb and please send me the screenshot of your error

**Comment by tobi-mb** [comment]
@psharanda The CarthageDemo doesn't compile for me because of absolute paths pointing to `/Users/psharanda/Github/Atributika` but even if it was, it's an iOS target. Whatever Carthage is compiling with `--platform macOS`, I don't think it's x86_64 / arm64, maybe Catalyst.

Here's a screenshot of when I try to build the Atributika framework with Release config for macOS on this branch with the latest changes:
image

**Comment by psharanda** [comment]
@tobi-mb I see now. Yeah interesting situation. Found this comment which explains what happened.

> Xcode 14.3 (released March 30, 2023) stopped building automatic reference counted (ARC) code targeting < iOS 9 or < macOS 10.11 by removing a libarclite_* library from the toolchain that was needed to link for these older targets.
> I also recommend filing issues with any pods you see hitting this to suggest they updated to a minimum of at least iOS 9 and macOS 10.11. For example https://github.com/openid/AppAuth-iOS/pull/761

**Pull request merged**
