### PR TITLE
Handled unescaped href Tags

### PR DESCRIPTION
**Pull request by lpizzinidev**
As suggested in issue #83

### CODE REVIEW

**Comment by psharanda** [comment]
Hi, this looks really great! Let me check it in depth

**Comment by psharanda** [comment]
@Pizzo15 Is it easy to support any name of attribute, not only href? Because right now, it is more like temporary solution for very specific use case.

**Comment by Pizzo15** [comment]
@psharanda I'll work on it.

**Comment by Pizzo15** [comment]
Just added unescaped support to all link tag attributes

**Pull request closed without merging**
